substitutions:
  device_name: dimled01
  friendly_name: DimLED 01
  default_brightness: 50%

packages:
  dimled.mk2: github://tqlabs-in/dimled/esphome/base.yaml@mark2
  # dimled.mk2:
  #   url: https://github.com/tqlabs-in/dimled
  #   files: [ esphome/base.yaml ]
  #   ref: mark2
  #   refresh: always
